### ISSUE TITLE
créer un footer avec menu basique et icones réseaux sociaux

### ISSUE THREAD

**Issue by Jetinho** [Jetinho/compost-lyon#51]

**Comment by TJBZH38** [comment]
Salut. J'ai préparé un footer en me basant sur UI component du Wagon. Il faudrait me dire quelles infos tu voudrais y mettre,  quels sont les liens pour les réseaux sociaux, ...

**Comment by KombiCode** [comment]
@Jetinho 
Salut. J'ai préparé un footer en me basant sur UI component du Wagon. Il faudrait me dire quelles infos tu voudrais y mettre, quels sont les liens pour les réseaux sociaux, ...
