### ISSUE TITLE
Ajouter dashboard admin

### ISSUE THREAD

**Issue by Jetinho** [Jetinho/compost-lyon#57]

**Comment by Jetinho** [comment]
@TJBZH38

**Comment by KombiCode** [comment]
@Jetinho 

Route pour accéder au dashboard : localhost:3000/admin

Il faut être connecté avec un user dont le champ 'admin' est positionné à true

Pour cela, faire par exemple : 

rails c
user = User.last
user.admin = true
user.save

**Comment by Jetinho** [comment]
Fait dans #59
