### ISSUE TITLE
Faire un drop de DB depuis heroku pour y avoir accès en local

### ISSUE THREAD

**Issue by Jetinho** [Jetinho/compost-lyon#82]

**Comment by KombiCode** [comment]
To Create Backup and download it do the following from command line
$ heroku pg:backups:capture -a compost
$ heroku pg:backups:download -a compost-lyon 
This will create a latest.dump file
Then to load the dump into our local database, use pg_restore tool as follows
pg_restore --verbose --clean --no-acl --no-owner -h localhost -U <username> -d CompostLyon_development latest.dump

**Comment by Jetinho** [comment]
@KombiCode tu as les accès heroku pour essayer chez toi ?
Quoi qu'il en soit faudra aussi que je le fasse de mon côté.

On peut regarder ça mercredi

**Comment by Jetinho** [comment]
@KombiCode pour faire le pg_restore t'as pas eu de problème de mot de passe ? 
Chez moi je galère car il me manque un mot de passe que j'ai pas.
